apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app-demo
data:
  FLASK_APP: flaskapp
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5000"
  VERSION: "1.2.0"
  SECRET_KEY: "deljl4556wsdfsczxa96s4s0mv"
  DATABASE: flaskapp.sqlite
  TESTING: "False" 
  SCRIPT_NAME: /flaskappdemo  