apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc-python-app-demo
  namespace: flask-app-demo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  # selector:
  #   matchLabels:
  #     release: "stable"
