apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mychart.fullname" . }}-sqlite-pvc-python-app-demo
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.sqlitePvcPythonAppDemo.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.sqlitePvcPythonAppDemo.storageClass | quote }}
  volumeMode: Filesystem